### ISSUE TITLE
Link changes

### ISSUE THREAD

**Issue by binarymist** [lirantal/picture-tuber#2]
Might want to update https://github.com/lirantal/picture-tuber/blob/master/package.json#L7 to your repo so that when users click on the github link in NPM it directs to your repo.

Also posibly consider removing the dead link in the README?

Cheers!

**Comment by lirantal** [comment]
Good catch, thanks!
I'll update those and be sure to update blessed-contrib's PR with the new version.

**Comment by lirantal** [comment]
@binarymist there are quite a few libs [dependent on picture-tube](https://www.npmjs.com/browse/depended/picture-tube), perhaps once we get this new one out it will make sense to find some of the actively maintained and offer a PR to make a similar exchange?

**Comment by binarymist** [comment]
Yip, I'd say so, I did exactly that with all the consumers of the old ZAP Node API to get them on the newly maintianed (https://github.com/zaproxy/zap-api-nodejs) and officially supported API ;-)

**Comment by lirantal** [comment]
Cool. Let's do that once we land the new one as part of blessed-contrib!
